packages:
  # include packages in subfolders (change as required)
  - 'apps/**'
  # all packages in direct subdirs of packages/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
