name: Deploy

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main
  # 手动触发部署
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # "最近更新时间" 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16
          cache: npm
      - run: npm install --frozen-lockfile

      # 运行构建脚本
      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 部署目录为 vitepress 的默认输出目录
          publish_dir: docs/.vitepress/dist
          # if want deploy to custom domain
          cname: learnku.fit
          # 部署到 gh-pages 分支
          target_branch: gh-pages
